version: '3'
services:
 db:
  image: mysql/mysql-server:latest
  container_name: mysql-db  
  environment:
   - MYSQL_ROOT_PASSWORD=123
   - MYSQL_USER=root
  ports:
   - "3306:3306"
  restart: always
 webapp:
  image: ayebnermin/timesheet
  container_name: timesheet-app
  build:
   context: .
   dockerfile: Dockerfile
  ports:
   - "8082:8082"
  restart: always
  depends_on:
   - db
  environment:
   SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/timesheet?createDatabaseIfNotExist=true
   SPRING_DATASOURCE_USERNAME: root
   SPRING_DATASOURCE_PASSWORD: 123